### ISSUE TITLE
Don't work on 3.4.1 Gatling

### ISSUE THREAD

**Issue by jigarkhwar** [TinkoffCreditSystems/gatling-picatinny#27]
```
java.lang.NoSuchMethodError: 'com.typesafe.config.Config io.gatling.core.config.GatlingConfiguration.config()'
 	at ru.tinkoff.gatling.config.ConfigManager$.gatlingConfig$lzycompute(ConfigManager.scala:18)
 	at ru.tinkoff.gatling.config.ConfigManager$.gatlingConfig(ConfigManager.scala:18)
 	at ru.tinkoff.gatling.influxdb.AnnotationManager$.<init>(AnnotationManager.scala:7)
 	at ru.tinkoff.gatling.influxdb.AnnotationManager$.<clinit>(AnnotationManager.scala)
 	at ru.tinkoff.gatling.influxdb.Annotations.$anonfun$$init$$1(Annotations.scala:8)
 	at io.gatling.core.scenario.Simulation.$anonfun$executeBefore$1(Simulation.scala:154)
 	at io.gatling.core.scenario.Simulation.$anonfun$executeBefore$1$adapted(Simulation.scala:154)
 	at scala.collection.immutable.List.foreach(List.scala:431)
 	at io.gatling.core.scenario.Simulation.executeBefore(Simulation.scala:154)
 	at io.gatling.app.Runner.run0(Runner.scala:70)
 	at io.gatling.app.Runner.run(Runner.scala:52)
 	at io.gatling.app.Gatling$.start(Gatling.scala:80)
 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 	at java.base/java.lang.Thread.run(Unknown Source)
 [error] Uncaught exception when running ru.tinkoff.load.mapi.DebugTest: java.lang.NoSuchMethodError: 'com.typesafe.config.Config io.gatling.core.config.GatlingConfiguration.config()'
 [error] sbt.ForkMain$ForkError: java.lang.NoSuchMethodError: 'com.typesafe.config.Config io.gatling.core.config.GatlingConfiguration.config()'
 [error] 	at ru.tinkoff.gatling.config.ConfigManager$.gatlingConfig$lzycompute(ConfigManager.scala:18)
 [error] 	at ru.tinkoff.gatling.config.ConfigManager$.gatlingConfig(ConfigManager.scala:18)
 [error] 	at ru.tinkoff.gatling.influxdb.AnnotationManager$.<init>(AnnotationManager.scala:7)
 [error] 	at ru.tinkoff.gatling.influxdb.AnnotationManager$.<clinit>(AnnotationManager.scala)
 [error] 	at ru.tinkoff.gatling.influxdb.Annotations.$anonfun$$init$$1(Annotations.scala:8)
 [error] 	at io.gatling.core.scenario.Simulation.$anonfun$executeBefore$1(Simulation.scala:154)
 [error] 	at io.gatling.core.scenario.Simulation.$anonfun$executeBefore$1$adapted(Simulation.scala:154)
 [error] 	at scala.collection.immutable.List.foreach(List.scala:431)
 [error] 	at io.gatling.core.scenario.Simulation.executeBefore(Simulation.scala:154)
 [error] 	at io.gatling.app.Runner.run0(Runner.scala:70)
 [error] 	at io.gatling.app.Runner.run(Runner.scala:52)
 [error] 	at io.gatling.app.Gatling$.start(Gatling.scala:80)
 [error] 	at io.gatling.app.Gatling$.fromArgs(Gatling.scala:45)
 [error] 	at io.gatling.sbt.GatlingTask.liftedTree1$1(GatlingTask.scala:52)
 [error] 	at io.gatling.sbt.GatlingTask.execute(GatlingTask.scala:51)
 [error] 	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
 [error] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 [error] 	at java.base/java.lang.Thread.run(Unknown Source)
```
